### PR TITLE
Clear recipients to avoid to send too much emails

### PR DESCRIPTION
**Pull request by maximehuran**
Clear recipient to avoid too much email sent

Done by the core :

image

Examples : 

image psd

### CODE REVIEW

**Comment by maximehuran** [comment]
Do you plan to review / merge this pull request ?

**Comment by borriglione** [comment]
Looks good, merged

**Comment by maximehuran** [comment]
Thank you @borriglione

**Comment by borriglione** [comment]
@maximehuran you're welcome. I'm not working on Magento anymore. But it seems some PRs in this repo seems worth to merge. If you're interested may ask @aschroder to add you to the list of allowed maintainers

**Pull request merged**
