### PR TITLE
SMTP Pro - Add migration from version 1.x to 2.x (for SES only)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
Fix for #76

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@aschroder any reasons to didn't merge it?

**Comment by aschroder** [comment]
I like the idea of what you're doing here and appreciate you submitted it back to the community, but 1.x to 2.x was a breaking upgrade in lots of ways - this being one of them. I think the use case is fairly limited, I just don't have the appetite to test this, even though I'm sure it works.

I'll leave this open and if I start getting a lot of complaints about this, I'll do something about it.

**Comment by sandermangel** [comment]
@aschroder this has been open for 1.5 years. Should we test the 2.x integration again or maybe close the PR for now?

**Comment by ihor-sviziev** [comment]
Seems like it will be never merged

**Pull request closed without merging**
